(()=>{
const toc=document.getElementById('portfolio-toc'),pill=document.getElementById('menu-open'),trigger=document.querySelector('.foundation-menu-trigger'),desktop=matchMedia('(min-width:1400px)'),links=[...toc.querySelectorAll('a')];let opened=false;
function setOpen(v){opened=v;toc.classList.toggle('is-open',v);pill.setAttribute('aria-expanded',String(v));trigger.setAttribute('aria-expanded',String(v));}
pill.onclick=()=>setOpen(!opened);trigger.onclick=()=>{setOpen(!opened);if(opened)links[0].focus()};desktop.addEventListener('change',()=>setOpen(false));
links.forEach(a=>a.addEventListener('click',e=>{const target=document.getElementById(a.hash.slice(1));if(!target)return;e.preventDefault();scrollTo({top:Math.max(0,target.getBoundingClientRect().top+scrollY-84),behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});history.replaceState(null,'',a.hash);if(!desktop.matches)setOpen(false)}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&opened){setOpen(false);pill.focus()}});document.addEventListener('click',e=>{if(opened&&!toc.contains(e.target)&&!pill.contains(e.target)&&!trigger.contains(e.target))setOpen(false)});
let queued=false;function update(){queued=false;let current=0;links.forEach((a,i)=>{const el=document.getElementById(a.hash.slice(1));if(el&&el.getBoundingClientRect().top<=innerHeight*.35)current=i});links.forEach((a,i)=>{if(i===current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});const a=links[current];pill.querySelector('.toc-pill-text').textContent=a.closest('.portfolio-toc-group').querySelector('h3').textContent+' · '+a.textContent;toc.classList.toggle('on-dark',['#components'].includes(a.hash));pill.querySelector('.toc-progress i').style.width=Math.min(100,Math.max(0,scrollY/(document.documentElement.scrollHeight-innerHeight||1)*100))+'%';}
addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(update)}},{passive:true});update();
const clock=document.getElementById('portfolio-clock');const tick=()=>clock.textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())+' IST';tick();setInterval(tick,1000);document.querySelectorAll('.portfolio-mobile a').forEach(a=>a.onclick=()=>document.querySelector('.portfolio-mobile').open=false);
})();
